import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// استيراد الخط من المجلد المحلي مع تحسين إدارة الأوزان
const nunitoSans = localFont({
  src: [
    {
      path: "../fonts/NunitoSans.ttf",
      weight: "400", // الوزن العادي
      style: "normal",
    },
    {
      path: "../fonts/NunitoSans.ttf",
      weight: "700", // الوزن العريض
      style: "normal",
    },
  ],
  variable: '--font-nunito-sans',
  display: 'swap', // تحسين الأداء باستخدام swap
});

export const metadata: Metadata = {
  title: "Web Store",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        {children} {/* تطبيق الخط الجديد */}
      </body>
    </html>
  );
}
